baseURL = "https://mirioeggmann.github.io/"
languageCode = "en"
title = "Mirio Eggmann"
theme = "hugo-coder"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "mirioeggmann"

[params]
    author = "Mirio Eggmann"
    description = "Mirio Eggmann's personal website"
    keywords = "blog,developer,personal"
    info = "Programmer. Crypto Enthusiast."
    avatarurl = "images/avatar.jpg"
    footercontent = ""

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Use inverted colors
    inverted = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/mirioeggmann/"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-instagram"
    weight = 2
    url = "https://instagram.com/mirioeggmann/"
[[params.social]]
    name = "Keybase"
    icon = "fab fa-keybase"
    weight = 3
    url = "https://keybase.io/mirioeggmann/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 4
    url = "https://twitter.com/mirioeggmann/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/mirioeggmann"

[languages]
    [languages.en]
        languagename = "English"

        [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "about/"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 2
        url = "posts/"
